name: app_ui
description: App UI library
version: 0.0.1
publish_to: none

environment: 
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.0.2
  flutter_svg: ^1.1.6

dev_dependencies:
  very_good_analysis: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: NotoSansDisplay
      fonts:
        - asset: assets/fonts/NotoSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansDisplay-SemiBold.ttf
          weight: 600
  

flutter_gen:
  assets:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80 

  integrations:
    flutter_svg: true