name: local_db
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  json_annotation: ^4.4.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.3.2

dev_dependencies:
  build_runner: ^2.1.0
  json_serializable: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

